Name:           ros-indigo-threemxl
Version:        0.2.0
Release:        2%{?dist}
Summary:        ROS threemxl package

Group:          Development/Libraries
License:        GPL
Source0:        %{name}-%{version}.tar.gz

Requires:       libftdi-c++-devel
Requires:       muParser-devel
Requires:       readline
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-shared-serial
Requires:       tinyxml-devel
BuildRequires:  libftdi-c++-devel
BuildRequires:  muParser-devel
BuildRequires:  pkgconfig
BuildRequires:  readline-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-shared-serial
BuildRequires:  tinyxml-devel

%description
Dynamixel and 3mxl driver

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Wouter Caarls <w.caarls@tudelft.nl> - 0.2.0-2
- Autogenerated by Bloom

